【課題】1から100までの数を標準出力
moroball14/fizzbuzz-moroball14 pull request #1
Opened 2021-01-05 05:55 UTC by moroball14

# 制約
言語: TypeScript
単体テスト: Jest + TypeScript
VCS: GitHub
実行: yarn start
テスト: yarn test
buildしてもts-nodeで実行しても良い
linterなどなくてOK
yarn ではなく npm でも問題なし
ライブラリの仕様はTA判断(今回izumikawaに報告)で可能

# 関連slack
https://corporate-bu.slack.com/archives/G01HX49AM9Q/p1609763152031100

2021-01-05 06:43 UTC, izumix03 requested changes
□時間内に達成するように計画、実行できたか: OK!!
■テストが正しく書けているか？: コメントしましたのでご確認お願いします:bow:
□GitHubに成果物がmasterブランチで提出できているか？: OK!!
□yarn startで1から100までプリントできるか？: OK!!
□カバレッジC0で100％か？: OK!!
□テストが全部成功するか？: OK!!
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.ts |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.127 s

2021-01-05 06:43 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  expect(JSON.stringify(counter.oneToHundred())).toBe(JSON.stringify(arr1_100));
[nits]
細かい部分で申し訳ありません。
toBeでは配列は比較できませんのでtoEqualの利用を検討してはいかがでしょうか？

参考: https://jestjs.io/docs/ja/using-matchers

2021-01-05 06:43 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  const arr1_100 = Array.from(new Array(100)).map((v,i)=> i + 1);
[nits]
細かいnitsです:bow:
この書き方だとvが不要なようなので少し変更して、
`Array.from(new Array(100).keys()).map((i)=> i + 1);` などはいかがでしょうか？

2021-01-05 06:43 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  expect(JSON.stringify(counter.oneToHundred())).toBe(JSON.stringify(arr1_100));
[お願い]
今回標準出力に出力することがポイントになります。

実開発では`.oneToHundred()` が返す値と標準出力が機能拡張していくうちに変更されることも考えられるので、 [Mock Function](https://jestjs.io/docs/ja/mock-function-api) を使ってみて頂けますでしょうか:bow:

2021-01-05 07:22 UTC, moroball14 commented on src/__tests__/index.test.ts
> +  expect(JSON.stringify(counter.oneToHundred())).toBe(JSON.stringify(arr1_100));
@izumix03
この記事が参考にできますでしょうか？

https://qiita.com/yuma-ito-bd/items/38c929eb5cccf7ce501e#%E9%96%A2%E6%95%B0%E3%82%92%E3%83%A2%E3%83%83%E3%82%AF%E3%81%AB%E3%81%97%E3%81%9F%E3%81%84

2021-01-05 07:39 UTC, moroball14 commented on src/__tests__/index.test.ts
> +  const arr1_100 = Array.from(new Array(100)).map((v,i)=> i + 1);
ありがとうございます！こちら修正しました。

2021-01-05 07:43 UTC, moroball14 commented on src/__tests__/index.test.ts
> +  expect(JSON.stringify(counter.oneToHundred())).toBe(JSON.stringify(arr1_100));
@izumix03
こちら修正していました。Mock Functionの使い方が正しいかが自信ないです。上記のQiita記事を参考にテストを記述しました。

2021-01-05 08:58 UTC, izumix03 requested changes

2021-01-05 08:58 UTC, izumix03 commented on src/__tests__/index.test.ts
> +jest.mock("../index");
[解説]
ここでmock化すると、indexが実際には動かず、テストできなくなってしまいます。

2021-01-05 08:58 UTC, izumix03 commented on src/__tests__/index.test.ts
> +jest.spyOn(console, "log")
[解説]
jest.spyOnはスパイ化した関数の情報にアクセスするための戻り値を取ります。
戻り値で返ってくるSpyInstanceから
・よびだされたかどうか
・何が引数によびだされたか
などが取れます

2021-01-05 08:58 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  expect(CounterMock).toHaveBeenCalled();
モック生成したかどうかの確認なので、
少し不思議なテストかもしれません。

2021-01-05 08:58 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  expect(console.log).toBeCalled();
[解説]
14行目での呼び出しのテストになっています。

2021-01-05 08:58 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  expect(return_ary).toEqual(arr1_100);
[解説]
15行目の確認になっていますので、テストとして上手く行っていないかもしれません。

2021-01-05 08:58 UTC, izumix03 commented
[IMO]
例えばの適当な例を記載します。
beforeEach使う、AfterEach使うなど改善の余地ありのサンプルです。

import { Counter } from "../index";

test("count 1 to 100", () => {
  const spyLog = jest.spyOn(console, "log")

  new Counter().oneToHundred()

  expect(spyLog.mock.calls).toHaveLength(100)
  Array.from(Array(100).keys()).forEach((i) => {
    expect(spyLog.mock.calls[i]?.[0]).toBe(i + 1)
  })

  spyLog.mockReset()
  spyLog.mockRestore()
});
愚直にテストするならこういうやり方もあります。
この場合 oneToHundredの戻り値 と標準出力に関連はないので、戻り値をなくすと良いです。

逆に戻り値を使ってconsole.logする場合は spy しなくても良いかと思います。

2021-01-06 02:58 UTC, moroball14 commented
memo
今回のテストコードについてまとめてみた
https://bitkey-misc.slack.com/archives/C01J031AH5H/p1609898048008600

2021-01-06 03:24 UTC, izumix03 approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/93916)

2021-01-06 03:24 UTC, izumix03 commented on README.md
> +
READMEが充実しているの素晴らしいですね！
![LGTM](https://cdn.lgtmoon.dev/images/15092)

2021-01-06 03:48 UTC, moroball14 commented on README.md
> +
ありがとうございます！！

2021-01-06 03:56 UTC, merged