【課題1-2】FizzBuzz
moroball14/fizzbuzz-moroball14 pull request #2
Opened 2021-01-06 07:40 UTC by moroball14

# 概要
1から100を標準出力、ただし3の倍数なら｢Fizz｣ 5の倍数なら｢Buzz｣ 両方の倍数なら｢Fizz Buzz｣と標準出力(それぞれカンマで区切ること)
例)1,2,Fizz,4,Buzz,.....14,Fizz Buzz,16,...Buzz

# 制約
言語: TypeScript
単体テスト: Jest + TypeScript
VCS: GitHub
実行: yarn start
テスト: yarn test
buildしてもts-nodeで実行しても良い
linterなどなくてOK
yarn ではなく npm でも問題なし
ライブラリの仕様はTA判断で可能

# 関連Slack
https://corporate-bu.slack.com/archives/G01HX49AM9Q/p1609915811110400

2021-01-06 07:48 UTC, moroball14 commented on src/__tests__/index.test.ts
> +});
3~10行目、今回特に変更が必要というわけではありませんが、前回の課題提出時にご指摘いただいたので、試しに変更してみました。
https://corporate-bu.slack.com/archives/G01HX49AM9Q/p1609903582102000?thread_ts=1609827099.052500&cid=G01HX49AM9Q

2021-01-06 10:06 UTC, izumix03 requested changes
□時間内に達成するように計画、実行できたか: OK
■テストが正しく書けているか？: NG
□カバレッジC0で100％か？(90%などでもOK,TA判断): OK
□テストが全部成功するか？
□GitHubに成果物がmasterブランチで提出できているか？
■yarn startで期待通り実行できるか？: NG
```
1から100を標準出力、ただし3の倍数なら｢Fizz｣ 5の倍数なら｢Buzz｣ 両方の倍数なら｢Fizz Buzz｣と標準出力(それぞれカンマで区切ること)
例)1,2,Fizz,4,Buzz,.....14,Fizz Buzz,16,...Buzz
```
ですので、カンマ区切りの出力を期待しています。

お手数おかけしますがご確認のほど宜しくお願い致します:bow:

2021-01-06 10:06 UTC, izumix03 commented on .gitignore
> +coverage
👍

2021-01-06 10:06 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  spyLog.mockReset();
素晴らしい！！

[nits]
申し訳ありません。
今回はテスト数が少ないので影響がありませんが、
以下の観点からちょっと提案させて下さい:bow:

・beforeEach / afterEach はブロックスコープなので、ブロックで囲まないとこのファイルの前テストの前と後に無駄に処理が走ってしまいます
→ describe で囲むのはいかがでしょうか？

・極力、let と var は使わないでconstで書くことを身に着けて欲しいです
　(再代入は必ずしも悪ではありませんがしなくてすむなら避けましょう！)
→`jest.restoreAllMocks()` などにしても良いかもしれません。
https://doc.ebichu.cc/jest/docs/ja/jest-object.html#jestrestoreallmocks

2021-01-06 10:06 UTC, izumix03 commented on src/__tests__/index.test.ts
> +});
チャレンジが素晴らしいです！！
ありがとうございます！

2021-01-06 10:06 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  const mockArray = spyLog.mock.calls;
👍

2021-01-06 10:06 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  expect(mockArray).toHaveLength(100);
[nits・雑談]
ループで全県確認せず正しいことを保証する必要十分は何かがポイントかもしれません。
ざっくり上げてみたもので抜けがるかもしれませんが下記などいかがでしょうか？

※抜けがあれば申し訳ありません。
・長さが100
・重複がない
・最小値が1
・最大値が100
・昇順ソートして比較しても同じ(1から順になっている)
・各要素がnumberである(小数などがない)

2021-01-06 10:06 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  expect(num % (3 * 5)).not.toBe(0);
[nits]
動作確認として良いです！

ただ実際に動く index.ts をテストするコードがテストコードなので
テストコードとしてはコミットしない方が良いかもしれません:bow:

2021-01-06 10:06 UTC, izumix03 commented on src/__tests__/index.test.ts
> +  expect(counter.returnFizzBuzz(num * (3 * 5))).toBe('Fizz Buzz');
[IMO]
ばっちりですね！

2点だけ提案させて下さい:bow:
①具体的な数字を使ってみましょう！
`num * (3 * 5)` の時 FIzz Buzz より `15` の時 の時 FIzz Buzzとした方がテストの意味がわかりやすいですよね。読みやすさはとても大切なのでぜひシンプルに書くことをやってみて下さい。

②保証するパターンを増やしてみましょう！
15のときの挙動は保証されていてOKです。
ですが、例えば30の場合に正しい挙動をするかは不明です。

※いや、自明やんけ！と思うかもしれませんが、
今後コードが変更されると仮定すると自明ではなくなってしまうという意味です:bow:

単体テストはデグレードを防ぐのが大きな役目なので、
できる限り結果を保証することを目指す必要があります。

保証方法は色々あります。
例えば一番愚直な方法だと、全ケース分テスト書くという方法もありです。
もっと良い方法ももちろんあるので考えてみて頂ければ幸いです。

2021-01-07 03:44 UTC, moroball14 commented on src/__tests__/index.test.ts
> +  expect(counter.returnFizzBuzz(num * (3 * 5))).toBe('Fizz Buzz');
こちら①②共に修正しました。
②に関しては、for文使って愚直にテスト書きつつなるべく少ないテストケースでおさまるよう考えてみましたので、ご確認お願いします！

2021-01-07 03:45 UTC, moroball14 commented on src/__tests__/index.test.ts
> +  expect(num % (3 * 5)).not.toBe(0);
こちら使用しないテストコードに変更したので削除しました！

2021-01-07 03:46 UTC, moroball14 commented on src/__tests__/index.test.ts
> +  expect(mockArray).toHaveLength(100);
今回console.logの呼び出しは一回のため、fizzbuzzで出力されるべき文字列が一致するかどうかのテストに変更しましたのでご確認お願いします！

2021-01-07 03:49 UTC, moroball14 commented on src/__tests__/index.test.ts
> +  spyLog.mockReset();
> → describe で囲むのはいかがでしょうか？
ありがとうございます！describeで囲みました。

> →jest.restoreAllMocks() などにしても良いかもしれません。
全てのモックをリセットするのですね！なるほどです。こちらに変更しました。
また、この変更に合わせて、beforeEachでモックを定義する意味がないように思えたので、モックの定義はテストケースの中で行うよう修正しました。

2021-01-07 05:21 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    counter.outputOneToHundred();
[IMO]
自分が間違ってたらすいません。
こちら利用していないと思うのですが、必要でしょうか？:bow:
```
counter.outputOneToHundred();
```

2021-01-07 05:21 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    };
[IMO]
こちらに関して、1点だけコメントさせていただきました！
testに if や for 文などのロジックを描くと、そのロジックが正しいかどうかの検証も必要になってくるので、できる限り、シンプルに、 `expect(A).toBe(B)`のような形にした方がいいかなと思います。

2021-01-07 05:27 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    counter.outputOneToHundred();
@jkkitakita

このメソッドの中で `console.log()` を呼んでいます。この記述がなかったら以下で定義した `spyLog` の中に、実行した履歴が残らないため、必要です！

```
const spyLog = jest.spyOn(console, "log");
```

2021-01-07 05:30 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    };
@jkkitakita
以下のやりとりがあって、正しい方法が思い付かずfor文の中でexpectを使ってしまいました、、
https://github.com/moroball14/fizzbuzz-moroball14/pull/2#discussion_r552479093

> 保証方法は色々あります。
例えば一番愚直な方法だと、全ケース分テスト書くという方法もありです。
もっと良い方法ももちろんあるので考えてみて頂ければ幸いです。

ここで言及されている良い方法のヒントがわかれば教えていただきたいです、、！

2021-01-07 05:51 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    counter.outputOneToHundred();
なるほどです。ありがとうございます！

2021-01-07 05:51 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    };
@moroball14 
なるほどです！先ほど見ました 🙇 

> ①具体的な数字を使ってみましょう！

こちらの指摘に関しては、四則演算（+-*/）などは使わずに、数字をそのまま渡すような形が良いという話かなと思いましたが、いかがでしょうか？
例えば、単純に `(3 * 5)` って書くよりも `15`って書いた方がわかりやすいよね？っていう
究極いうとそれだけ伝えたかったのかなと感じましたが、いかがでしょうか？ 🤔 
多分、そう考えると、for文もすっきり見えそうな気がします。

> ②保証するパターンを増やしてみましょう！

こっちの話も↑やると解消するかも？
ちょっと考えてみてもらえると 🙇

2021-01-07 07:03 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    };
①for文は使わないで保証するパターンを愚直に増やすには以下のように定数を代入する
②for文を使って100までのパターンを網羅的にテストする
の二つを考えてみました。
個人的には②が良いと思ったのですが、@jkkitakita さんがおっしゃりたいのはこういうことであってますでしょうか、、？（いまいち要点が掴めないでいます、、）

①省略して書いてます（1から順に書くのが良い？）↓
```
expect(counter.returnFizzBuzz(45)).toBe('Fizz Buzz');
expect(counter.returnFizzBuzz(30)).toBe('Fizz Buzz');
expect(counter.returnFizzBuzz(15)).toBe('Fizz Buzz');
expect(counter.returnFizzBuzz(9)).toBe('Fizz');
expect(counter.returnFizzBuzz(6)).toBe('Fizz');
expect(counter.returnFizzBuzz(3)).toBe('Fizz');
expect(counter.returnFizzBuzz(20)).toBe('Buzz');
expect(counter.returnFizzBuzz(10)).toBe('Buzz');
expect(counter.returnFizzBuzz(5)).toBe('Buzz');
expect(counter.returnFizzBuzz(4)).toBe((4).toString());
expect(counter.returnFizzBuzz(2)).toBe((2).toString());
expect(counter.returnFizzBuzz(1)).toBe((1).toString());
```

②
```
for (let i = 1; i <= 100; i++) {
  if (i % 15 === 0) {
    expect(counter.returnFizzBuzz(i)).toBe('Fizz Buzz');
  } else if (i % 3 === 0) {
    expect(counter.returnFizzBuzz(3)).toBe('Fizz');
  } else if (i % 5 === 0) {
    expect(counter.returnFizzBuzz(5)).toBe('Buzz');
  } else {
    expect(counter.returnFizzBuzz(i)).toBe(i.toString());
  };
};
```

2021-01-07 07:17 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    };
@moroball14 

丁寧にありがとうございます！

> 個人的には②が良いと思ったのですが、@jkkitakita さんがおっしゃりたいのはこういうことであってますでしょうか、、？（いまいち要点が掴めないでいます、、）

わかりづらく、申し訳ございません。。
はい。意図としては正にそういう話でした！！！ありがとうございます！！！

> ②for文を使って100までのパターンを網羅的にテストする

私も個人的にはこれがいい感じかなと思ってます！
（①はちょっとわかりづらい、かつ、冗長、保守性がないので。）
あと修正するとすると

1. `counter.returnFizzBuzz(5)`とかは、iではなく、数値を入れた意図は何かありますでしょうか？
2. `counter.returnFizzBuzz(i)` など何回も出てくるので、一度変数にするとかすると、文字数も減って、見やすくなるかなと思いましたが、いかがでしょうか？ :bow:
    - 何回も同じこと書いているなと思ったら、ちょっと違和感を感じる癖をつけるといいアイデアが出てきたりすると思います！

2021-01-07 08:22 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    };
@jkkitakita

> counter.returnFizzBuzz(5)とかは、iではなく、数値を入れた意図は何かありますでしょうか？

これは記述ミスです、すみません！

> counter.returnFizzBuzz(i) など何回も出てくるので、一度変数にするとかすると、文字数も減って、見やすくなるかなと思いましたが、いかがでしょうか？ 

ありがとうございます！共通化するよう意識していましたが、漏れていました！一度指摘された事項を [リスト](https://docs.google.com/spreadsheets/d/1o8qyP5Syj3xiwWGbCqwcHCxPawugfXpvLMkPx-zReII/edit#gid=0) にまとめているので、今後はレビューお願いする前に確認します！

2021-01-07 09:12 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    };
[IMO]
テスト的には、ほぼ完成しててきているのですが
↑の部分など、できる限り、テストコードではロジックを
書かない方が個人的にいいかなと思っています。

例えば、このテストケースだと

`counter.outputOneToHundred()`のみの結果が正しいかどうか
を確認したいケースかなと思っているのでそれ以外の要素、例えば

1. 他の関数（e.g. counter.returnFizzBuzz(i)）はできる限り使わない
    - 期待値となる `fizzbuzz` は、多少長くても可能な範囲なら、別途constとかで定義しちゃうのもありだと思います。
2. for、ifなどもできる限り使わない。（使う場合は↓のように、分かりやすさを意識すること）
https://github.com/moroball14/fizzbuzz-moroball14/pull/2/files#diff-d88e65f56079eff48d6b092d57fb8c9be81f913cdb64b55b0b1012cdae90a029R24

とかの方がいいかなと思っていますが、いかがでしょうか？ :bow:

2021-01-07 09:12 UTC, jkkitakita commented on lib/index.js
> +        console.log(fizzbuzz.slice(0, -1));
[IMO]
ちょっと細かいかもしれませんが、ここの記述の部分では

1. console.logへ出力する
2. 出力結果を整形する

の二つの操作をしているかと思うのですが
今後の保守性なども考えると、テストが失敗したときに

1. console.logが呼ばれなかったのか
2. 整形に失敗したのか

の区別が付かなくなる可能性があるかなと感じたので

> 2. 出力結果を整形する

方の処理をする関数を `outputOneToHundred`から切り出してみてもいいかなと
思ったりしましたが、いかがでしょうか？ 🙇 
（その関数自体のテストも必要ですが、、多分、今後に生きてくるような気がしています。。？）

2021-01-07 09:24 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    expect(typeof mockArray[0][0]).toBe("string");
[IMO]
型を常に意識するのを癖づけるのはすごい大事だと思います！
なので、継続してもらうのが良いと思います！

ただ、、↓の記述に
```
It calls Object.is to compare values, which is even better for testing than === strict equality operator.
```
とあるので、やらなくてもいいかもしれないと思いましたが、いかがでしょうか？ :bow:
https://jestjs.io/docs/ja/expect#tobevalue

2021-01-07 09:24 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    expect(mockArray).toHaveLength(1);
[確認]
ここに関しては
ちょっと自分がjestわかっていないからかもなので
教えていただきたいのですが
この行で確認したいこととしては

「console.logを呼び出された回数が、1回であること」

であっていますでしょうか？ 🤔 

もしそうであれば、↓とかも使った方が分かりやすいかなと
思ったりしましたがいかがでしょうか？ 🙇 
https://jestjs.io/docs/ja/expect#tohavebeencalledtimesnumber

2021-01-07 09:40 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    };
> 期待値となる fizzbuzz は、多少長くても可能な範囲なら、別途constとかで定義しちゃうのもありだと思います。

なるほどです。すべてロジックから整形するものだと思っていました（根拠はないです）。修正しました！

> for、ifなどもできる限り使わない。（使う場合は↓のように、分かりやすさを意識すること）

これは今後も意識していきたいと思います。使っても良い場面と使うべきでない場面の住み分けがまだ自分の中でできていないのでまた質問させていただくかもしれません！！ご迷惑おかけして申し訳ないですが、よろしくお願いします  🙇

2021-01-07 09:42 UTC, moroball14 commented on lib/index.js
> +        console.log(fizzbuzz.slice(0, -1));
ありがとうございます！修正しました！

> 出力結果を整形する

切り出すべきか迷い、処理が少ないかつ限定的だから切り出しませんでした、、
確かに保守性を考えると、切り分けるべきだと気づくことができました！

2021-01-07 09:43 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    expect(typeof mockArray[0][0]).toBe("string");
ドキュメントをしっかり読めておらず申し訳ございません、、こちらのテストを削除しました。

2021-01-07 09:46 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    expect(mockArray).toHaveLength(1);
> 「console.logを呼び出された回数が、1回であること」
であっていますでしょうか？ 

はい！あっています！

> もしそうであれば、↓とかも使った方が分かりやすいかなと
思ったりしましたがいかがでしょうか？ 🙇
https://jestjs.io/docs/ja/expect#tohavebeencalledtimesnumber

完全に同意です。ありがとうございます！

ちなみに、こちらの方が適切なのではないか、というメソッド（今回で言うとマッチャー）を見つけるために意識していることはありますでしょうか？（マッチャーを全て把握しているから指摘できたわけではないと文脈から判断したので、、）

2021-01-07 09:50 UTC, jkkitakita commented on src/__tests__/index.test.ts
>    });
[雑談]
ちょっといろいろ他の人のPRとかもみてたのですが、そうか。
あんまり if / for 使わないように言われてたんですね。。申し訳ございません :bow:
https://github.com/moroball14/fizzbuzz-moroball14/pull/2#discussion_r552476458
まぁでもいったんここは大丈夫ですが、今後あんまり使わないように意識してもらえればと思いますー！

2021-01-08 01:34 UTC, jkkitakita reviewed
もうほぼかけているので、ほぼ終わりの認識ですが、細かいところコメントいたしました！！
```
□ 時間内に達成するように計画、実行できたか？
□ カバレッジC0で100％か？
□ テストが全部成功するか？
□ GitHubに成果物がmasterブランチで提出できているか？
□ yarn startで正しく動く？
■ テストが正しく書けているか？: コメント記載したのでご確認お願いします:bow:
```

2021-01-08 01:34 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    expect(mockArray[0][0]).toBe(fizzbuzz);
[コメント]
- 一度しか呼ばれていないこと
- またその結果と期待値が、完全一致していること

を確認できているので、必要十分な気がしています！ :tada:

2021-01-08 01:34 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +  test("output 1 to 100", () => {
[nits]
本テストの名前が適切ではない気がするのですが、前の課題の名残ですかね？ 🤔 
またここの概要に記載する書き方はいろいろあるのですが
`should`とか`must be`とかの言葉を使って
概要に「どうあるべき状態をテストしているのか」を、より具体的に記載してあげた方がいいかなと思います！
「このテストケースって何をテストしてたんだっけ？」ってなったときに、「あーそうだそうだ」ってなるような文言がいいですね！
このテストケースで言えば、↓の「2通りをテストしていること」をこの概要に表現できるといいかなと個人的には思います！（人によっては違うかもなので、他の人が違うこと言ってたらすいません。。。）
他のテストケースに関しても、同様に見直してみていただければと思います！

```
expect(spyLog).toHaveBeenCalledTimes(1);
expect(mockArray[0][0]).toBe(fizzbuzz);
```

あと、雑談ですが、結構、私も

- コメント
- ログ出力の文字列

とか修正忘れたりするので、今のうちに意識していただけるとよきかなと思います、、！ 🙇

2021-01-08 01:36 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    expect(mockArray[0][0]).toBe(fizzbuzz);
ありがとうございます！！

2021-01-08 01:44 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    expect(mockArray).toHaveLength(1);
@moroball14 
確認ありがとうございます！！よかったです！

>ちなみに、こちらの方が適切なのではないか、というメソッド（今回で言うとマッチャー）を見つけるために意識していることはありますでしょうか？（マッチャーを全て把握しているから指摘できたわけではないと文脈から判断したので、、）

意識していることでいうと、、完全に個人的な意見ですが

1. 「パッとみてわかるかどうか」
2. 俺レベルの悩みなんて、絶対同じように他の人も悩んでいるはずだ！

ってところですかね。

> 1. 「パッとみてわかるかどうか」

今回でいうと `length`の比較しているけど
「これなんの長さなんだっけ？」ってのが「パッとわからない。」とちょっと感じてしまいました :bow:
`spyLog`の仕様を理解している人であれば
無意識に理解できるかもですが、私のような初心者にはパッとわからなかったです笑

> 2. （俺レベルの悩みなんて）絶対同じように他の人も悩んでいるはずだ！

なんかないかなーと、↓眺めてたら、なんかそれっぽいの見つけた。
https://jestjs.io/docs/ja/expect#tohavebeencalledtimesnumber

みたいな流れですね。笑

2021-01-08 01:48 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    };
> なるほどです。すべてロジックから整形するものだと思っていました（根拠はないです）。修正しました！

確かに結構最初はこれでいいんだっけ？って感じにもなりますが
分かりやすさを優先すると「確かに」みたいな感じになる時も結構ありますね！
かなり複雑になってくるとロジックで生成する話になるかもですが
普通に生きてれば、あまりないかもです。笑

>これは今後も意識していきたいと思います。

私もすいません。。
私もまだまだなので、一緒に頑張りましょう。。。！ 🙇

2021-01-08 01:53 UTC, jkkitakita commented on src/__tests__/index.test.ts
> +    expect(typeof mockArray[0][0]).toBe("string");
@moroball14 
確認ありがとうございます！
それぞれの `expect`が何を確認しているのかを意識すると
「テストの必要十分」に関しても少し見えてくるかもと思いました！

なので

「テストの必要十分ってなんだよ！わからん！」

ってなったら、↓を眺めてみて
https://jestjs.io/docs/ja/expect#tohavebeencalledtimesnumber

「世の中のテストはどういうメソッドが用意されているのか」
から帰納的に
「どういうテストが必要十分たり得るのか」
を考えてみるのも一つの方法かなと思いました。

2021-01-08 02:11 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    };
> 最初はこれでいいんだっけ？って感じにもなります

まさにこうなってました（笑）
テストにおけるスタンダードを知れて良かったです！

2021-01-08 02:20 UTC, moroball14 commented on src/__tests__/index.test.ts
> +  test("output 1 to 100", () => {
> shouldとかmust beとかの言葉を使って
概要に「どうあるべき状態をテストしているのか」を、より具体的に記載してあげた方がいいかなと思います！

テストケースの概要にshouldとmustを加えました！

> コメント
ログ出力の文字列
とか修正忘れたりするので、今のうちに意識していただけるとよきかなと思います、、！

承知しました！ありがとうございます！

2021-01-08 02:24 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    expect(mockArray).toHaveLength(1);
確かに僕この一週間はずっとspyLogの中身をデバッグして確認したりと、少し慣れてきた（本当に本当に本当に少しですが）部分はあってパッと見でわからないコードを書いてしまった感じはありますね、、
また、適切なマッチャーがあることを調べずにレビュー依頼してしまった節はありますので、今後気をつけます！

2021-01-08 02:35 UTC, jkkitakita approved these changes
課題1-2に関しては、okかなと思います！🎉 

```
□ 時間内に達成するように計画、実行できたか: Excellent!!
□ カバレッジC0で100％か？
□ テストが全部成功するか？
□ GitHubに成果物がmasterブランチで提出できているか？
□ yarn startで正しく動く？
□ テストが正しく書けているか？
```

![image](https://user-images.githubusercontent.com/11452854/103967515-86536c80-51a5-11eb-84db-0f424140a04d.png)

2021-01-08 02:38 UTC, moroball14 commented on src/__tests__/index.test.ts
> +    expect(typeof mockArray[0][0]).toBe("string");
なるほど！！！必要十分条件をメソッドから考えてみるのはやってなかったです！次はこの方法も試したいと思います！

2021-01-08 02:42 UTC, merged